<?php
/**
 * Oxygen Builder Custom Element Boilerplate (Elements API)
 *
 * This structural class extends \OxyEl to register a custom drag-and-drop 
 * element inside the Oxygen Builder interface.
 * 
 * Usage: Place this inside a custom plugin or snippet manager.
 */

// Ensure the class is only declared after Oxygen VSB has initialized
add_action('plugins_loaded', function() {
    
    // Safety check: only run if Oxygen's core element class is available
    if (class_exists('OxyEl')) {

        class OxyCustomProfileCard extends OxyEl {

            /**
             * The readable name of the element as it appears in the builder UI.
             */
            public function name() {
                return 'Profile Card';
            }

            /**
             * The internal slug used by Oxygen (prepends ct_ automatically).
             * Resulting shortcode: [ct_my_profile_card]
             */
            public function slug() {
                return 'my_profile_card'; 
            }

            /**
             * The category/tab where this element should be placed in the "+ Add" sidebar.
             */
            public function button_place() {
                return 'custom_components'; // e.g., 'basics', 'helpers', 'wordpress'
            }

            /**
             * The SVG icon displayed next to the element name.
             */
            public function icon() {
                return '<svg viewBox="0 0 24 24"><path fill="currentColor" d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z"/></svg>';
            }

            /**
             * Define the visual CSS controls available in the left sidebar for this element.
             */
            public function controls() {
                
                // Add a text input field (data saved in $options array)
                $this->addOptionControl(
                    array(
                        "type"  => "textfield",
                        "name"  => "Name Text",
                        "slug"  => "profile_name"
                    )
                );

                $this->addOptionControl(
                    array(
                        "type"  => "textfield",
                        "name"  => "Role Text",
                        "slug"  => "profile_role"
                    )
                );

                // Add a structural CSS control tied to the wrapper
                $this->addStyleControl(
                    array(
                        "name"     => "Card Background Color",
                        "selector" => ".oxy-profile-card", // The class applied to the root element
                        "property" => "background-color"
                    )
                );
            }

            /**
             * Renders the HTML output on the frontend and inside the builder.
             *
             * @param array  $options  User-saved property values from controls()
             * @param array  $defaults Default property values
             * @param string $content  Child elements (if this element acts as a container)
             */
            public function render($options, $defaults, $content) {
                // Fetch the values, fallback to strings if empty
                $name = isset($options['profile_name']) ? $options['profile_name'] : 'John Doe';
                $role = isset($options['profile_role']) ? $options['profile_role'] : 'Developer';
                ?>

                <!-- 
                    Root wrapper: It's crucial to output elements with stable classes.
                    The styles generated by the style controls will target these classes.
                -->
                <div class="oxy-profile-card">
                    <div class="oxy-profile-header">
                        <h3 class="oxy-profile-name"><?php echo esc_html($name); ?></h3>
                        <p class="oxy-profile-role"><?php echo esc_html($role); ?></p>
                    </div>
                    
                    <?php 
                    // Render any internal child drag-and-drop elements dropped into this element
                    if (!empty($content)) { 
                    ?>
                        <div class="oxy-profile-children-content">
                            <?php echo do_shortcode($content); ?>
                        </div>
                    <?php 
                    } 
                    ?>
                </div>

                <?php
            }

            /**
             * Output custom CSS directly into the Oxygen global stylesheet.
             * Useful for structural CSS that shouldn't be edited by the user.
             */
            public function customCSS($original, $selector) {
                $css = "
                    $selector .oxy-profile-card {
                        display: flex;
                        flex-direction: column;
                        padding: 1.5rem;
                        border-radius: 8px;
                        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
                    }
                    $selector .oxy-profile-name {
                        margin: 0;
                        font-size: 1.25rem;
                        font-weight: 700;
                    }
                    $selector .oxy-profile-role {
                        margin-top: 0.25rem;
                        color: #666;
                        font-size: 0.875rem;
                    }
                    $selector .oxy-profile-children-content {
                        margin-top: 1rem;
                        border-top: 1px solid #eee;
                        padding-top: 1rem;
                    }
                ";
                return $css;
            }
        }

        // Initialize the element mapping
        new OxyCustomProfileCard();

    }
});
